import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { verifySession } from "@/lib/dal";
import { requirePermission } from "@/lib/authorize";
import { logAction } from "@/lib/audit-log";
import { apiError, apiSuccess } from "@/lib/api-response";
import { isValidEmployeeType } from "@/lib/validation";
import { computeNextNumber, findNextFreeEmployeeCode, getOrCreateDocumentNumber } from "@/lib/document-number";

const NEW_EMPLOYEE_DOCUMENT_CODE = "NEW_EMPNO";

export async function GET() {
  const user = await verifySession();
  if (!user) return apiError(401, "UNAUTHORIZED");
  const denied = await requirePermission(user, "EMPLOYEE", "read");
  if (denied) return denied;

  const employees = await prisma.mstEmployee.findMany({
    select: {
      EmpCode: true,
      FullName: true,
      EmployeeStatus: true,
      EmployeeType: true,
      DeptCode: true,
      PositionCode: true,
      DefaultSiteCode: true,
      IsActive: true,
    },
    orderBy: { EmpCode: "asc" },
  });
  return apiSuccess(employees);
}

export async function POST(request: NextRequest) {
  const user = await verifySession();
  if (!user) return apiError(401, "UNAUTHORIZED");
  const denied = await requirePermission(user, "EMPLOYEE", "save");
  if (denied) return denied;

  let body: {
    empCode?: unknown;
    idCardNo?: unknown;
    title?: unknown;
    firstName?: unknown;
    lastName?: unknown;
    deptCode?: unknown;
    positionCode?: unknown;
    startDate?: unknown;
    employeeType?: unknown;
    referrerEmpCode?: unknown;
    confirmDuplicateIdCard?: unknown;
  };
  try {
    body = await request.json();
  } catch {
    return apiError(400, "INVALID_PARAMS", "Request body must be JSON");
  }

  const empCode = typeof body.empCode === "string" ? body.empCode.trim() : "";
  const idCardNo = typeof body.idCardNo === "string" ? body.idCardNo.trim() : "";
  const title = typeof body.title === "string" ? body.title.trim() : "";
  const firstName = typeof body.firstName === "string" ? body.firstName.trim() : "";
  const lastName = typeof body.lastName === "string" ? body.lastName.trim() : "";
  const startDate = typeof body.startDate === "string" ? body.startDate : "";

  if (!empCode || !idCardNo || !title || !firstName || !lastName || !startDate) {
    return apiError(400, "INVALID_PARAMS", "empCode, idCardNo, title, firstName, lastName, and startDate are required");
  }
  if (!isValidEmployeeType(body.employeeType)) {
    return apiError(400, "VALIDATION_FAILED", "employeeType must be one of the allowed values");
  }

  // EmpCode collisions used to be a hard block; now (2026-09-19) they're
  // auto-resolved by generating a fresh code from the NEW_EMPNO running
  // sequence — only falling back to the hard 409 if that sequence isn't
  // configured (or is "กำหนดเอง"/IsCustomNumber, which has no sequence to
  // generate from). finalEmpCode is what actually gets created; empCode
  // stays the originally-submitted value for the response/log.
  //
  // 2026-09-24 concurrency fix: resolving finalEmpCode (the findUnique
  // check + findNextFreeEmployeeCode's own scan) and the actual INSERT are
  // separate round-trips, so two concurrent requests can both resolve to
  // the SAME free-looking code and only one wins the real INSERT (EmpCode
  // is mst_employee's primary key) — confirmed via a live 10-concurrent-
  // request test (LOCK-002) that crashed 9/10 requests with an unhandled
  // 500 instead of a clean result. resolveFinalEmpCode() is now re-run on
  // a P2002 (primary-key collision) instead of letting it bubble up as a
  // 500 — a request that loses the race just picks the next free code and
  // tries again, up to a few attempts (collisions this many times in a row
  // would mean something is actually wrong, not just unlucky timing).
  async function resolveFinalEmpCode() {
    const existingEmpCode = await prisma.mstEmployee.findUnique({ where: { EmpCode: empCode } });
    if (existingEmpCode) {
      const generated = await findNextFreeEmployeeCode(NEW_EMPLOYEE_DOCUMENT_CODE);
      if (!generated) return { error: apiError(409, "EMPLOYEE_ALREADY_EXISTS", undefined, { empCode }) } as const;
      return { finalEmpCode: generated.code, autoGenerated: true, latestNumberToConsume: generated.consumedLatestNumber } as const;
    }
    const docNum = await getOrCreateDocumentNumber(NEW_EMPLOYEE_DOCUMENT_CODE, "รหัสพนักงานใหม่");
    const latestNumberToConsume =
      !docNum.IsCustomNumber && computeNextNumber(docNum.LatestNumber, docNum.UseYearMonthPrefix) === empCode
        ? docNum.LatestNumber + 1
        : null;
    return { finalEmpCode: empCode, autoGenerated: false, latestNumberToConsume } as const;
  }

  let finalEmpCode: string;
  let autoGenerated: boolean;
  let latestNumberToConsume: number | null;
  {
    const resolved = await resolveFinalEmpCode();
    if ("error" in resolved) return resolved.error;
    ({ finalEmpCode, autoGenerated, latestNumberToConsume } = resolved);
  }

  // IDCardNo is no longer UNIQUE (2026-09-19) — a person can be re-hired
  // under a new EmpCode after resigning. Surface any prior record(s) under
  // this ID card and let the user confirm before creating a duplicate.
  if (body.confirmDuplicateIdCard !== true) {
    const priorMatches = await prisma.mstEmployee.findMany({
      where: { IDCardNo: idCardNo },
      select: { EmpCode: true, FullName: true, EmployeeStatus: true, ResignDate: true },
      orderBy: { StartDate: "desc" },
    });
    if (priorMatches.length > 0) {
      const blacklistEntry = await prisma.refBlackList.findFirst({ where: { IDCardNo: idCardNo } });
      return apiError(409, "ID_CARD_DUPLICATE_NEEDS_CONFIRM", undefined, {
        matches: priorMatches,
        blacklist: blacklistEntry,
      });
    }
  }

  const fullName = [title, firstName, lastName].filter(Boolean).join(" ").trim();

  // 20, not 5 — a live 10-concurrent-request test (LOCK-002) against a
  // single shared starting EmpCode still exhausted 5 retries for 2-3 of the
  // 10 requests (each retry's findNextFreeEmployeeCode() scan can itself
  // land on a candidate another in-flight request is also about to claim,
  // so a few collisions in a row isn't rare under this much contention).
  const MAX_EMPCODE_COLLISION_RETRIES = 20;
  let created: Awaited<ReturnType<typeof prisma.mstEmployee.create>> | undefined;
  let exhausted = false;
  for (let attempt = 0; attempt < MAX_EMPCODE_COLLISION_RETRIES; attempt++) {
    try {
      [created] = await prisma.$transaction([
        prisma.mstEmployee.create({
          data: {
            EmpCode: finalEmpCode,
            IDCardNo: idCardNo,
            Title: title,
            FirstName: firstName,
            LastName: lastName,
            FullName: fullName,
            StartDate: new Date(startDate),
            DeptCode: typeof body.deptCode === "string" && body.deptCode ? body.deptCode : null,
            PositionCode: typeof body.positionCode === "string" && body.positionCode ? body.positionCode : null,
            EmployeeType: body.employeeType,
            ReferrerEmpCode: typeof body.referrerEmpCode === "string" && body.referrerEmpCode.trim() ? body.referrerEmpCode.trim() : null,
            CreatedBy: user.userId,
          },
        }),
        // BR-011: 5 quota rows exist for every employee from day one (limit 0 until HR sets one).
        prisma.mstEmployeeQuota.createMany({
          data: (["ADVANCE", "LOAN", "UNIFORM", "SERVICE", "INSURANCE"] as const).map((QuotaType) => ({
            EmpCode: finalEmpCode,
            QuotaType,
          })),
        }),
        ...(latestNumberToConsume !== null
          ? [
              prisma.refDocumentNumber.update({
                where: { DocumentCode: NEW_EMPLOYEE_DOCUMENT_CODE },
                data: { LatestNumber: latestNumberToConsume, UpdatedBy: user.userId, UpdatedDate: new Date() },
              }),
            ]
          : []),
      ]);
      break;
    } catch (err) {
      // Duck-typed check instead of `instanceof Prisma.PrismaClientKnownRequestError`
      // — that instanceof check silently always failed here in testing (never
      // caught anything, error always rethrown), because Turbopack compiles
      // each Route Handler as its own bundle and this route's `Prisma` import
      // ended up a DIFFERENT module instance than the one tenant-registry.ts's
      // dynamically-created PrismaClient actually threw its error from — the
      // exact same class of bug already hit (and fixed with a globalThis
      // singleton) for tenant-context.ts's AsyncLocalStorage; see CLAUDE.md's
      // "Multi-tenant" entry. A plain `.code` check is immune to that, since
      // it only reads a string property, not a class identity.
      //
      // Not narrowing to err.meta?.target === "EmpCode" specifically — the
      // mssql driver doesn't reliably populate which column a P2002 came
      // from, and EmpCode (mst_employee's primary key) is the only
      // contended uniqueness this transaction touches, so any P2002 here is
      // presumed to be that collision.
      const isCollision = typeof err === "object" && err !== null && "code" in err && err.code === "P2002";
      if (!isCollision) throw err;
      if (attempt === MAX_EMPCODE_COLLISION_RETRIES - 1) {
        // Retries genuinely exhausted under extreme contention — return a
        // clean, retryable error instead of letting the raw Prisma
        // exception escape as an unhandled 500 (the client can just POST
        // again; the whole point of this loop was to avoid needing that,
        // but it has to have a bounded worst case).
        exhausted = true;
        break;
      }

      const resolved = await resolveFinalEmpCode();
      if ("error" in resolved) return resolved.error;
      ({ finalEmpCode, autoGenerated, latestNumberToConsume } = resolved);
    }
  }
  if (exhausted || !created) {
    return apiError(409, "EMPCODE_ALLOCATION_CONFLICT", "Could not allocate a free employee code under heavy concurrent load — please try again");
  }

  await logAction(user.userId, "CREATE_EMPLOYEE", { targetTable: "mst_employee", targetId: finalEmpCode });
  return apiSuccess({ ...created, empCodeAutoGenerated: autoGenerated, requestedEmpCode: autoGenerated ? empCode : undefined }, 201);
}
