import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { verifySession } from "@/lib/dal";
import { requirePermission } from "@/lib/authorize";
import { logAction } from "@/lib/audit-log";
import { apiError, apiSuccess } from "@/lib/api-response";
import { isValidEmployeeType } from "@/lib/validation";
import { computeNextNumber, findNextFreeEmployeeCode, getOrCreateDocumentNumber } from "@/lib/document-number";

const NEW_EMPLOYEE_DOCUMENT_CODE = "NEW_EMPNO";

export async function GET() {
  const user = await verifySession();
  if (!user) return apiError(401, "UNAUTHORIZED");
  const denied = await requirePermission(user, "EMPLOYEE", "read");
  if (denied) return denied;

  const employees = await prisma.mstEmployee.findMany({
    select: {
      EmpCode: true,
      FullName: true,
      EmployeeStatus: true,
      EmployeeType: true,
      DeptCode: true,
      PositionCode: true,
      DefaultSiteCode: true,
      IsActive: true,
    },
    orderBy: { EmpCode: "asc" },
  });
  return apiSuccess(employees);
}

export async function POST(request: NextRequest) {
  const user = await verifySession();
  if (!user) return apiError(401, "UNAUTHORIZED");
  const denied = await requirePermission(user, "EMPLOYEE", "save");
  if (denied) return denied;

  let body: {
    empCode?: unknown;
    idCardNo?: unknown;
    title?: unknown;
    firstName?: unknown;
    lastName?: unknown;
    deptCode?: unknown;
    positionCode?: unknown;
    startDate?: unknown;
    employeeType?: unknown;
    referrerEmpCode?: unknown;
    confirmDuplicateIdCard?: unknown;
  };
  try {
    body = await request.json();
  } catch {
    return apiError(400, "INVALID_PARAMS", "Request body must be JSON");
  }

  const empCode = typeof body.empCode === "string" ? body.empCode.trim() : "";
  const idCardNo = typeof body.idCardNo === "string" ? body.idCardNo.trim() : "";
  const title = typeof body.title === "string" ? body.title.trim() : "";
  const firstName = typeof body.firstName === "string" ? body.firstName.trim() : "";
  const lastName = typeof body.lastName === "string" ? body.lastName.trim() : "";
  const startDate = typeof body.startDate === "string" ? body.startDate : "";

  if (!empCode || !idCardNo || !title || !firstName || !lastName || !startDate) {
    return apiError(400, "INVALID_PARAMS", "empCode, idCardNo, title, firstName, lastName, and startDate are required");
  }
  if (!isValidEmployeeType(body.employeeType)) {
    return apiError(400, "VALIDATION_FAILED", "employeeType must be one of the allowed values");
  }

  // EmpCode collisions used to be a hard block; now (2026-09-19) they're
  // auto-resolved by generating a fresh code from the NEW_EMPNO running
  // sequence — only falling back to the hard 409 if that sequence isn't
  // configured (or is "กำหนดเอง"/IsCustomNumber, which has no sequence to
  // generate from). finalEmpCode is what actually gets created; empCode
  // stays the originally-submitted value for the response/log.
  let finalEmpCode = empCode;
  let autoGenerated = false;
  // Set when this creation should advance ref_document_number.LatestNumber
  // for NEW_EMPNO — either because a fresh code was generated from it, or
  // because the submitted EmpCode matches what the sequence would currently
  // suggest (i.e. the user accepted the "Add Employee" page's prefill as-is).
  let latestNumberToConsume: number | null = null;

  const existingEmpCode = await prisma.mstEmployee.findUnique({ where: { EmpCode: empCode } });
  if (existingEmpCode) {
    const generated = await findNextFreeEmployeeCode(NEW_EMPLOYEE_DOCUMENT_CODE);
    if (!generated) return apiError(409, "EMPLOYEE_ALREADY_EXISTS", undefined, { empCode });
    finalEmpCode = generated.code;
    autoGenerated = true;
    latestNumberToConsume = generated.consumedLatestNumber;
  } else {
    const docNum = await getOrCreateDocumentNumber(NEW_EMPLOYEE_DOCUMENT_CODE, "รหัสพนักงานใหม่");
    if (!docNum.IsCustomNumber && computeNextNumber(docNum.LatestNumber, docNum.UseYearMonthPrefix) === empCode) {
      latestNumberToConsume = docNum.LatestNumber + 1;
    }
  }

  // IDCardNo is no longer UNIQUE (2026-09-19) — a person can be re-hired
  // under a new EmpCode after resigning. Surface any prior record(s) under
  // this ID card and let the user confirm before creating a duplicate.
  if (body.confirmDuplicateIdCard !== true) {
    const priorMatches = await prisma.mstEmployee.findMany({
      where: { IDCardNo: idCardNo },
      select: { EmpCode: true, FullName: true, EmployeeStatus: true, ResignDate: true },
      orderBy: { StartDate: "desc" },
    });
    if (priorMatches.length > 0) {
      const blacklistEntry = await prisma.refBlackList.findFirst({ where: { IDCardNo: idCardNo } });
      return apiError(409, "ID_CARD_DUPLICATE_NEEDS_CONFIRM", undefined, {
        matches: priorMatches,
        blacklist: blacklistEntry,
      });
    }
  }

  const fullName = [title, firstName, lastName].filter(Boolean).join(" ").trim();

  const [created] = await prisma.$transaction([
    prisma.mstEmployee.create({
      data: {
        EmpCode: finalEmpCode,
        IDCardNo: idCardNo,
        Title: title,
        FirstName: firstName,
        LastName: lastName,
        FullName: fullName,
        StartDate: new Date(startDate),
        DeptCode: typeof body.deptCode === "string" && body.deptCode ? body.deptCode : null,
        PositionCode: typeof body.positionCode === "string" && body.positionCode ? body.positionCode : null,
        EmployeeType: body.employeeType,
        ReferrerEmpCode: typeof body.referrerEmpCode === "string" && body.referrerEmpCode.trim() ? body.referrerEmpCode.trim() : null,
        CreatedBy: user.userId,
      },
    }),
    // BR-011: 5 quota rows exist for every employee from day one (limit 0 until HR sets one).
    prisma.mstEmployeeQuota.createMany({
      data: (["ADVANCE", "LOAN", "UNIFORM", "SERVICE", "INSURANCE"] as const).map((QuotaType) => ({
        EmpCode: finalEmpCode,
        QuotaType,
      })),
    }),
    ...(latestNumberToConsume !== null
      ? [
          prisma.refDocumentNumber.update({
            where: { DocumentCode: NEW_EMPLOYEE_DOCUMENT_CODE },
            data: { LatestNumber: latestNumberToConsume, UpdatedBy: user.userId, UpdatedDate: new Date() },
          }),
        ]
      : []),
  ]);

  await logAction(user.userId, "CREATE_EMPLOYEE", { targetTable: "mst_employee", targetId: finalEmpCode });
  return apiSuccess({ ...created, empCodeAutoGenerated: autoGenerated, requestedEmpCode: autoGenerated ? empCode : undefined }, 201);
}
